### ISSUE TITLE
Dependency conflict when installing the required packages

### ISSUE THREAD

**Issue by JeanKossaifi** [pdebench/PDEBench#1]
Trying to install the requirements (even in a new venv as recommended in the README) results in a dependency conflict:
```
INFO: pip is looking at multiple versions of pandas to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 10), -r requirements.txt (line 12), -r requirements.txt (line 13), -r requirements.txt (line 15), -r requirements.txt (line 16), -r requirements.txt (line 18), -r requirements.txt (line 2), -r requirements.txt (line 3), -r requirements.txt (line 4), -r requirements.txt (line 5) and numpy~=1.22.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy~=1.22.3
    scipy 1.8.0 depends on numpy<1.25.0 and >=1.17.3
    matplotlib 3.5.2 depends on numpy>=1.17
    h5py 3.6.0 depends on numpy>=1.14.5
    pandas 1.4.2 depends on numpy>=1.18.5; platform_machine != "aarch64" and platform_machine != "arm64" and python_version < "3.10"
    pytorch-lightning 1.6.3 depends on numpy>=1.17.2
    clawpack 5.6.1 depends on numpy>=1.14
    deepxde 1.1.3 depends on numpy
    jax 0.3.13 depends on numpy>=1.19
    jaxlib 0.3.10 depends on numpy>=1.19
    phiflow 2.0.3 depends on numpy==1.19.5

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by timothypraditia** [comment]
Hi there, thanks for the report.

Inferring from the error message, it seems that the bug originates from the numpy version (phiflow seems to require exactly version 1.19.5). Could you please try by removing the numpy version specification? Or set it to 1.19.5?

**Comment by JeanKossaifi** [comment]
Thanks, that fixed it. The other issue has been with clawpack which I had to install through conda-forge. 
Generally it would be great to have installation instructions for users using conda!

**Comment by leiterrl** [comment]
Great to hear! Regarding clawpack: Yes, apparently the pip package has been broken for a while in combination with `setuptools>61` (https://github.com/clawpack/clawpack/issues/211). We will provide an updated requirements.txt file to include the relevant upstream patch (https://github.com/clawpack/clawpack/pull/212).

**Comment by leiterrl** [comment]
The requirements are now updated. Additionally, as you suggested, I added installation instructions for using conda to the README.
