### ISSUE TITLE
Data download issue from python script

### ISSUE THREAD

**Issue by cheliu-computation** [pdebench/PDEBench#14]
Hi, Thanks for your brilliant work first!

I am trying to download data from Sttutgart platform through download.py. However, I always face error message: KeyError: 'project', 
and UserWarning: No 'API_TOKEN' found in the environment. Please be aware, that you might not have the rights to download this dataset.

If I go to the benchmarks dataset homepage and download by the link, everything is going well, the only problem is downloading through the download.py script.
I did not change any configuration in config.yaml, so I think the problem might be in other places.

**Comment by leiterrl** [comment]
Hi,

the "UserWarning: No 'API_TOKEN' ... " is safe to ignore since the dataset is public and no authentication is needed. The other error however is due to a recent update of the pyDaRUS library. We are looking into it.

**Comment by cheliu-computation** [comment]
> Hi,
> 
> the "UserWarning: No 'API_TOKEN' ... " is safe to ignore since the dataset is public and no authentication is needed. The other error however is due to a recent update of the pyDaRUS library. We are looking into it.

Thanks for your effort!
Looking forward to seeing the update.

**Comment by kmario23** [comment]
In the meantime, please comment out the following lines in your easyDataverse installation:

https://github.com/gdcc/easyDataverse/blob/main/easyDataverse/tools/downloader/downloader.py#L100
https://github.com/gdcc/easyDataverse/blob/main/easyDataverse/tools/downloader/downloader.py#L101

Specifically, the file can be found in a path like:

> home/mario/anaconda3/envs/pdebench/lib/python3.9/site-packages/easyDataverse/tools/downloader/downloader.py
And then comment out lines 100 and 101. 

After that the download script should work.

**Comment by leiterrl** [comment]
So we just pushed a new script for easier access to the dataset called `download_direct.py`. Check the newly added Readme for examples on how to use it and feel free to report any issues.

**Comment by kmario23** [comment]
Hence closing it now. Please reopen if you still encounter issues.
