### ISSUE TITLE
How to use the downloaded 3D dataset

### ISSUE THREAD

**Issue by xiaojun-mbed** [pdebench/PDEBench#16]
I downloaded the 3D_CFD_Turb_M1.0_Eta1e-08_Zeta1e-08_periodic_Train.hdf5 file, but I didn't find a specific way to use the dataset, or a specific description of that dataset. 

Meanwhile, I downloaded the 3DCFD_FNO.tar pre-trained weights file, how can I use this file?

**Comment by mtakamoto-D** [comment]
Thank you very much for your interest. 

If you want to simply perform training, it could be done by modifying examples in "run_forward_1D.sh", for example, as: 
`CUDA_VISIBLE_DEVICES='0' python3 train_models_forward.py +args=config_3DCFD.yaml`

The explanation for using pretrained weight would be provided soon.

**Comment by xiaojun-mbed** [comment]
Thank you very much for your reply.
When I look at the 3D_CFD_Turb_M1.0_Eta1e-08_Zeta1e-08_periodic_Train.hdf5 dataset, I get the output as shown. What dimension does 600 represent? Does this represent different numerical simulations with 600 initial conditions, etc.? Do you provide details of this dataset?
![3D_CFD](https://user-images.githubusercontent.com/54529051/204182854-5e799294-0e0b-424b-a516-0f44dd72778f.png)

**Comment by kmario23** [comment]
`600` is the number of samples, `21` is the number of timesteps, `64x64x64` is the spatial resolution as mentioned in section 4.4 in the paper here [PDEBENCH: An Extensive Benchmark for Scientific Machine Learning](https://arxiv.org/abs/2210.07182).
