### ISSUE TITLE
3D CFD with M=0.1

### ISSUE THREAD

**Issue by JacobHelwig** [pdebench/PDEBench#18]
I trained FNO3D on the dataset `3D_CFD_Rand_M1.0_Eta1e-08_Zeta1e-08_periodic_Train.hdf5`. I also generated an identical dataset with `M=0.1`. I used spatial resolution `64 x 64 x 64`. Here are my results, with `M=0.1` in blue and `M=1` in red.

![image](https://user-images.githubusercontent.com/60412857/205728863-0bde624a-1b52-4835-815a-c768e303c4e7.png)

For reference, here is the training log at the last epoch for `M=1`:

```
epoch: 499, loss: 10.87719, t2-t1: 35.52373, trainL2: 18.71870, testL2: 20.85403
```

It is not surprising that the `M=1` problem is harder, but a 40-times increase is very high and makes me wonder how realistic the predicted rollouts are. 

I observed a similar result in the 2D case with the files `2D_CFD_Rand_M1.0_Eta0.01_Zeta0.01_periodic_128_Train.hdf5` and `2D_CFD_Rand_M0.1_Eta1e-08_Zeta1e-08_periodic_512_Train.hdf5`, trained on resolution `64 x 64`. 

![image](https://user-images.githubusercontent.com/60412857/205729447-03769769-4c48-4bef-bde3-ae8695a2a383.png)

Would it be possible to have an official `M=0.1` 3D dataset released on Darus for those that may want to benchmark CFD with M=0.1 for not only 2D CFD (as is currently available), but 3D as well?

**Comment by kmario23** [comment]
We have the dataset and are exploring the options to release it at the earliest possible.
