### ISSUE TITLE
Code error

### ISSUE THREAD

**Issue by nevoliu** [pdebench/PDEBench#21]
Hello!
This work of yours has been a strong support to drive innovation in machine learning simulation and I thank you for your contribution.
I was recently studying your project code and I found that in the Inverse/train.py file, FNO3d is incorrectly written as FNO2d when initializing the model. 
When I am using analyse_result_forward.py, I cannot find the *pickle file, where can I go to find it.
By the way, what files and commands are needed to run the code for the Inverse problem?

**Comment by falesiani** [comment]
Dear nevoliu, 

thank you for your comment, the code has been updated. 

Kind Regards
