### ISSUE TITLE
How to get more picture of result

### ISSUE THREAD

**Issue by wszs8921** [pdebench/PDEBench#25]
Hi,
After I trained the PINN model and ran analyse_result_forward.py,I got the Result.pdf.There are only the images about MSE.
How can I get more information of the result?Such as the visualized data and visualized prediction or anything else,just like the pictures shown in your paper.

**Comment by timothypraditia** [comment]
Hi there, we have added a script to visualize and animate the data: [visualize_pdes.py](https://github.com/pdebench/PDEBench/blob/main/pdebench/data_download/visualize_pdes.py). This is unfortunately still incomplete, and we are still working on it.
