### ISSUE TITLE
Form of shallow water equations 

### ISSUE THREAD

**Issue by JacobHelwig** [pdebench/PDEBench#27]
Here are the shallow water equations on Wikipedia (https://en.wikipedia.org/wiki/Shallow_water_equations):

![image](https://user-images.githubusercontent.com/60412857/211895589-fe62c098-7b92-4907-af80-42b586a56283.png)

Setting the density `rho=1`, these agree with the equations given by Pyclaw: https://github.com/clawpack/pyclaw/blob/858498a9e2e2876519d4544bae4020675c0283e0/examples/shallow_2d/radial_dam_break.py#L10

However the equations in the supplementary material are quite different on the right-hand side:

![image](https://user-images.githubusercontent.com/60412857/211896253-bcb811e5-2b4d-4617-bc29-ef80071164e8.png)

For example, the derivatives are with respect to `x` in the second equation and `y` in the third equation, and there is no product of `u` and `v`. A key difference is that the pyclaw and wikipedia equations assume that the bathymetry is constant, but I do not see how this would rectify the other differences I mentioned.

Another related question I have is whether the bathymetry is actually spatially varying, or is it constant everywhere. If it varies spatially, how is it defined in terms of `x` and `y`?

**Comment by leiterrl** [comment]
To summarize a discussion our exchange we had via E-Mail:

- The mixed terms in the appendix where indeed missing
- The bathymetry in the example is constant but still listed in the equations for the sake of completeness
- You can find the PDE that in the code for training the PINN here: https://github.com/pdebench/PDEBench/blob/main/pdebench/models/pinn/pde_definitions.py#L64

The equations in code are written in what is sometimes referred to as non-conservative form. This is achieved by expanding the derivative products and using the continuity equation.
