### ISSUE TITLE
Data generation for DarcyFlow problem

### ISSUE THREAD

**Issue by anirudhs96** [pdebench/PDEBench#29]
Hi, are there scripts to generate data for DarcyFlow problem?

[data_gen_NLE](https://github.com/pdebench/PDEBench/blob/main/pdebench/data_gen/data_gen_NLE) contain scripts for other problems.

Thank you,
Anirudh

**Comment by mtakamoto-D** [comment]
Hi. Thank you very much for your kindly pointing out our mistake. 
DarcyFlow data can be generated using 
`data_gen/data_gen_NLE/ReactionDiffusionEq/reaction_diffusion_2D_multi_soluion_Hydra.py`
The detailed procedure is as: 
1. run `data_gen/data_gen_NLE/ReactionDiffusionEq/run_DarcyFlow2D.sh`
2. set `data_gen/data_gen_NLE/config/config.yaml` as: 
`type: 'ReacDiff'  # 'advection'/'ReacDiff'/'burgers'/'CFD'`
`dim: 2`
3. run `data_gen/data_gen_NLE/Data_Merge.py`

Please feel free to ask questions if the above is insufficient. 
Best,

**Comment by kmario23** [comment]
Closing it now. If unresolved, please reopen the issue.
