### ISSUE TITLE
2D Incompressible Navier-Stocks Dataset

### ISSUE THREAD

**Issue by JiahaoHuang99** [pdebench/PDEBench#31]
Hi,

Thanks so much for your great job!

When I check the data [page](https://darus.uni-stuttgart.de/dataset.xhtml?persistentId=doi:10.18419/darus-2986), I found there are so many repeat `ns_incom_inhom_2d_512-275.h5`. Are they the same or the wrong file name?

Thanks.

**Comment by kmario23** [comment]
This has been fixed in the latest update of the dataset. 

https://darus.uni-stuttgart.de/dataset.xhtml?persistentId=doi:10.18419/darus-2986
