### ISSUE TITLE
2D Darcy Flow Training

### ISSUE THREAD

**Issue by rtu715** [pdebench/PDEBench#34]
What is the right command for running [the Darcy Flow config](https://github.com/pdebench/PDEBench/blob/main/pdebench/models/config/args/config_Darcy.yaml)? When initial_step is set to 10, t_train is only 2 as read from the data. This means that the code does not enter the training loop.

**Comment by kmario23** [comment]
Hey @rtu715, 
 Thanks for raising this issue. DarcyFlow is time-independent and hence the `t_train` parameter is 1. Therefore, we cannot use AR mode for training. In the [provided DarcyFlow config file](https://github.com/pdebench/PDEBench/blob/main/pdebench/models/config/args/config_Darcy.yaml#L30), replace the `autoregressive` with `single`, and then pass the `training_type` kwarg when you call the `run_training_FNO(...)` in `train_models_forward.py`. After these changes, you can use the same training command as with the other PDEs to train an FNO model for example.

**Comment by rtu715** [comment]
Closing since this is resolved. Thank you!
