### ISSUE TITLE
Using Relative Error Metrics?

### ISSUE THREAD

**Issue by arthurfeeney** [pdebench/PDEBench#37]
(this is more of a question than an issue, but I suppose it sort of works as a feature request :-3)

Hi, thanks for the awesome dataset!

I noticed in [neuraloperator](https://github.com/neuraloperator/neuraloperator/blob/main/neuralop/training/losses.py), they use relative error metrics/loss function for training (see [implementation](https://github.com/neuraloperator/neuraloperator/blob/main/neuralop/training/losses.py) and [use](https://github.com/neuraloperator/neuraloperator/blob/main/examples/plot_FNO_darcy.py#L55)). AFAIK, PDEBench does not use relative metrics for training or evaluation (?) 

Do you think it would make sense to include similar relative errors? Or is there any particular reason y'all chose to exclude the relative errors in PDEBench?

**Comment by arthurfeeney** [comment]
oops, sorry for the noise, I completely forgot y'all use normalized RMSE 😵‍💫

**Comment by JiahaoHuang99** [comment]
Hi @arthurfeeney, I have the same question about this. Do you mean "When you use nRMSE, it doesn't matter which loss function for training?"

Thanks a lot.
