### ISSUE TITLE
Issue on the computation of numerical errors for 2D-Darcy

### ISSUE THREAD

**Issue by liu-ziyuan-math** [pdebench/PDEBench#41]
Hi @leiterrl and @kmario23,

Consider the darcy flow $$\nabla \cdot (a \nabla u) = 1.$$
When computing the RMSE in `/model/metric.py`, the program will minus `[a, u_pred]` with `[a, u_ref]`, rather than `u_pred - u_ref`. It make no difference for MSE but I guess it may underestimate the (relative) L2 norm error (i.e. RMSE and nRMSE in the paper), because it will double the N on the denominator.

I add some temporary code to illustrate the point on Line 177, you can see the `pred` is doubled on the last channel-dim and the first channel of `pred - target` all equal zeros. See
https://github.com/liu-ziyuan-math/PDEBench-testl2/blob/main/pdebench/models/metrics.py

I'm not sure if it occur only in the 2D-Darcy problem but I presume it should be so since the 2D-darcy is the only time independent problem in the datasets.

**Comment by mtakamoto-D** [comment]
Thank you very much for your pointing out. 
Actually we found this is a common issue for the present PDEBench performance evaluation: 
The present metric.py includes initial input (typically 10 to 20 initial time-step) as "prediction" which induces an overestimation of the model performance. 
We are now discussing if we would modify the code without initial input part in the prediction and update at least the arXiv paper with the newly evaluated scores. 
Thanks again for your kind contribution!

**Comment by liu-ziyuan-math** [comment]
Thanks!
