### ISSUE TITLE
Issue on the grid of data

### ISSUE THREAD

**Issue by liu-ziyuan-math** [pdebench/PDEBench#43]
Greatings, authors, and sorry to bother you again with questions.

In the dataset, the mesh of the domain (e.g. 1-d interval `[a, b]`) would not include the points on the boundary, i.e. `a` and `b`. For Dirichlet BC, values on the boundaries are given by the B.C. so that users can fill them up by themselves. For Neumann BC, however, only the 1st derivatives are known and the boundary value can be essential for checking the boundary condition errors of learning models, and I find it not very trivial to recover the them. In addition, it's common to give and use the boundary value of solutions in many datasets/models. I wonder how can I get the boundary values in the datasets, especially the 2D diff-react data.

I look forward to hearing from you soon.

**Comment by liu-ziyuan-math** [comment]
Seems to get the part of point after asking. While other PDE-ML datasets are on the collocated grids, functions in PDEBench datasets are on the staggered grid, so it may not be that easy to approximate the Neumann BC error...

**Comment by leiterrl** [comment]
Hi, I assume this is resolved then? Please reopen if you need further assistance.
