### ISSUE TITLE
Release ?

### ISSUE THREAD

**Issue by thomas-bouvier** [pdebench/PDEBench#44]
Hello,

Thank you for this package. Are you planning to release a tarball, or even a PyPi release anytime soon? I would like to write a [Spack](https://github.com/spack/spack) recipe and this is required.

Thank you!

**Comment by kmario23** [comment]
Hey @thomas-bouvier,
  Yes, we're planning on releasing one, prolly by next week. Will update here once it's done.

**Comment by thomas-bouvier** [comment]
Thank you very much.

**Comment by kmario23** [comment]
@thomas-bouvier It'll take a couple more days. Apologies for the delay.

**Comment by kmario23** [comment]
@thomas-bouvier Thanks to @leiterrl here we go with [releases/tag/v0.1.0](https://github.com/pdebench/PDEBench/releases/tag/v0.1.0). Please let us know if you'd like more help or face issues with the Spack packaging.

**Comment by thomas-bouvier** [comment]
Thank you very much :)

Will be working on a Spack recipe.
