### ISSUE TITLE
Getting error while downloading dataset

### ISSUE THREAD

**Issue by Karn3003** [pdebench/PDEBench#45]
Hi, I tried downloading the Darcy flow dataset using the following command.
python download_direct.py --root_folder $proj_home/data --pde_name darcy

Getting the following error:
RuntimeError: File not found or corrupted.

**Comment by leiterrl** [comment]
Hi, could you provide the complete stacktrace and (maybe as a first guess) make sure that the folder you are trying to save to already exists?

**Comment by Karn3003** [comment]
Yeah the folder where I am trying to save already exists.

**Comment by Karn3003** [comment]
I tried via wget and it worked for me. Also, is the dataset normalized??

**Comment by Karn3003** [comment]
Also can you please send me the URL for compressible Navier-Stokes 3D as I am not able to find it.

Thanks

**Comment by leiterrl** [comment]
You can find the files on DaRUS here: https://darus.uni-stuttgart.de/dataset.xhtml?persistentId=doi:10.18419/darus-2986

I suggest you to switch to the Tree view where you can navigate to 3D/Train where you should find three different files. You can find the specific download URL in the details view for each file.

**Comment by Karn3003** [comment]
Okay, Thanks it worked for me.
