### ISSUE TITLE
Scaling issue for 1D Advection data

### ISSUE THREAD

**Issue by apivich-h** [pdebench/PDEBench#46]
From Fig. 6 of the paper (in the Appendix):

![image](https://github.com/pdebench/PDEBench/assets/100082199/b2db0794-f200-4c81-8224-1aada25ae696)

Based on the closed form of the formula (Appendix D1), I feel the right-hand chart seems to have inconsistent scaling in time dimension compared to the PDE, i.e. the time value should be 2 times what the y-axis of the graph says, or beta should be double the value.

I also find a similar problem from the downloaded file from the url listed in `data_download`, where the dataset for the Advection dataset doesn't seem to be consistent with the Advection formula due to the similar scaling issue (based on just observing the array in the returned object).

Thanks in advance for your response.

**Comment by mtakamoto-D** [comment]
Thank you very much for your kind pointing out! 
Actually it results from a very silly typo in the code generating code that has been fixed in the latest version. 
The regenerated dataset will be released soon. We are also preparing for an update of arXiv paper with recalculated results on the new dataset..

**Comment by mtakamoto-D** [comment]
It is only for advection equation. 
We are now reassessing all the data generation code. We update the code and data if we found any issues.

**Comment by kmario23** [comment]
Hi @apivich-h,
  The code and datasets have been updated addressing the issue. The new datasets are already available on the [PDEBENCH - DARUS](https://darus.uni-stuttgart.de/dataset.xhtml?persistentId=doi:10.18419/darus-2986) repository.
