### ISSUE TITLE
Range of the x-coordinate for 1D Burgers data

### ISSUE THREAD

**Issue by functoreality** [pdebench/PDEBench#51]
Thank you a lot for this benchmark dataset. In Appendix D.3 of the paper, the range of the x-axis is (0, 1) according to equation (11,12).
![Screenshot_20231027_104930](https://github.com/pdebench/PDEBench/assets/63465198/6e07c2bc-4e26-4cc7-973b-c42c6dd844ba)
However, in Fig.7, the range is (-1, 1) according to the curves, and (0, 1) according to the two-dimensional plot.
![Screenshot_20231027_103936](https://github.com/pdebench/PDEBench/assets/63465198/5d54df46-7cbc-4805-b439-27522fc5441b)
In the configuration files for data generation, the range appears to be (-1, 1) as well:
https://github.com/pdebench/PDEBench/blob/4361430bd3704914ff6ed4fd737aaeb272354f19/pdebench/data_gen/data_gen_NLE/BurgersEq/config/multi/1e-2.yaml#L6-L7
For the dataset I downloaded:
```python
with h5py.File('1D_Burgers_Sols_Nu0.01.hdf5', "r") as h5_file:
    print(h5_file['x-coordinate'][:])
# [-0.99902344 -0.9970703  -0.9951172  ...  0.9951172   0.9970703   0.99902344]
```
This seems a bit confusing to me. 

Furthermore, if the range of the x-axis is (-1, 1), then I find a scaling issue similar to the Advection data mentioned [here](https://github.com/pdebench/PDEBench/issues/46). If I have not misunderstood, for the Burgers equation, the shock propagates at a speed of (uL + uR) / 2. According to the first panel of Fig.7, the average of uL and uR is approximately -0.8, but the propagation speed seems to be doubled. I wonder whether this is related to the following lines in the data generation script:
https://github.com/pdebench/PDEBench/blob/4361430bd3704914ff6ed4fd737aaeb272354f19/pdebench/data_gen/data_gen_NLE/BurgersEq/burgers_multi_solution_Hydra.py#L265-L266
In the updated script for the Advection equation, the value of the flux is multiplied by 0.5, but this operation is not applied here for the Burgers equation. 

Thanks in advance for your response.

**Comment by kmario23** [comment]
Thank you for bringing this up! We have implemented the fix in the latest commit https://github.com/pdebench/PDEBench/commit/5f199875d7581e8a4fc2ccc768ade71798237d8f

The new dataset and results will be updated in the next upload of the paper.
