### ISSUE TITLE
Configuration file for FNO on SWE equation

### ISSUE THREAD

**Issue by HaoZhongkai** [pdebench/PDEBench#52]
Dear authors,
Thanks for the nice benchmark as well as the data!
I have a question about using FNO for shallow-water equation 2D (SWE). It seems there is only a configuration file for PINNs on this PDE. 
I want to know in which file is the configuration file or hyperparameters of FNO on SWE 2D?

best regards

**Comment by kmario23** [comment]
Hi @HaoZhongkai,
  Thank you for your kind interest in our benchmark and bringing this issue to our notice. I have added the support for training an FNO with [SWE-2D dataset ](https://darus.uni-stuttgart.de/file.xhtml?fileId=133021&version=6.0).
  
 The corresponding config file is now located at [pdebench/models/config/config_rdb.yaml](https://github.com/pdebench/PDEBench/blob/main/pdebench/models/config/config_rdb.yaml), but this is just for convenience (see original here: [pdebench/models/config/args/config_rdb.yaml](https://github.com/pdebench/PDEBench/blob/main/pdebench/models/config/args/config_rdb.yaml) ).
 
Download the [Radial Dam Break data](https://darus.uni-stuttgart.de/file.xhtml?fileId=133021&version=6.0) to an appropriate path, update its absolute path in the config file [pdebench/models/config/config_rdb.yaml#L22](https://github.com/pdebench/PDEBench/blob/main/pdebench/models/config/config_rdb.yaml#L22), then do:

```
$ python train_models_forward.py
```

You can adjust the desired parameters such as spatial and temporal subsampling, number of modes in FNO, batch size, lr, how many initial steps you wanna use as initial condition (i.e., `initial_step`) etc., in the config file.
