### ISSUE TITLE
Config files for provided pretrained models

### ISSUE THREAD

**Issue by Winfriedvdd** [pdebench/PDEBench#6]
Hi!

I was wondering if there are specific config files or further details available somewhere for all the pretrained models that are provided? I see that there are some under models/config/args, but there are also many missing from this folder it seems.

It would be nice to have specific information per pretrained model (e.g., which resolutions have been used, architectures, whether ar_mode has been used, pushforward, what initial_step, etc.) as I am currently struggling a bit with properly loading each pretrained model as well as mimicking the test results in the paper. 

Kind regards,

Winfried

**Comment by GeoffNN** [comment]
+1 on this -- I've not yet been able to load/train a model. I've only tried 1D advection and Burgers so far, will update with further results.

**Comment by timothypraditia** [comment]
Hi @Winfriedvdd and @GeoffNN, many thanks for your feedback. I've put an initial draft of the [config documentation](https://github.com/pdebench/PDEBench/blob/main/pdebench/models/config/config_docs.md).
We will complete this documentation as soon as possible :)

**Comment by timothypraditia** [comment]
Thanks for the suggestion, we’ll look into it.

**Comment by kmario23** [comment]
The issue with paths was resolved in this commit https://github.com/pdebench/PDEBench/commit/245610307ed024d043638d6de0f506bec4b26267

**Comment by GeoffNN** [comment]
Thanks! I'll look into it soon ; I haven't had the bandwith recently.

Happy holidays!
