### ISSUE TITLE
What is the VLlimiter?

### ISSUE THREAD

**Issue by cyhuangx** [pdebench/PDEBench#60]
Hi,

I'm curious about what this VLlimiter is. It does not look like the Van Leer flux limiter. Do you have any reference paper or source of this so I can look into it? Thanks a lot.
https://github.com/pdebench/PDEBench/blob/bf6a33b17cabe78a0c44df93d826b4cdee11740b/pdebench/data_gen/data_gen_NLE/utils.py#L1342-L1345

**Comment by mtakamoto-D** [comment]
Hi. It's the van Leer limiter without if sentences. 
Or at least a variation of it. 
One of references is 
https://crd.lbl.gov/assets/pubs_presos/AMCS/ANAG/A141984.pdf
