### ISSUE TITLE
Broken `download_metadata.csv`

### ISSUE THREAD

**Issue by juliusberner** [pdebench/PDEBench#62]
As the title suggests, in the last commit the file `download_metadata.csv` seems to have turned into a binary, leading to an error for `pd.read_csv(...)`. Reverting to the old commit, solves the issue for now.

**Comment by kmario23** [comment]
Dear @juliusberner,

   Thank you for spotting this and bring it to our notice. I've fixed the issue in commit https://github.com/pdebench/PDEBench/commit/dcc94b86c46bb2f1a7881c104c17fc423464df6c 
  
 Additionally, you should now be able to inspect the urls from [pdebench/data_download/pdebench_data_urls.csv](https://github.com/pdebench/PDEBench/blob/main/pdebench/data_download/pdebench_data_urls.csv)
