### ISSUE TITLE
Downloading for compressible NS equation

### ISSUE THREAD

**Issue by liluo2** [pdebench/PDEBench#63]
Hi! Thanks for a good work here! I have a question here.

As I check on compressible NS equation of your dataset, I found that there are some trajectory like:
![2024-04-25 175610](https://github.com/pdebench/PDEBench/assets/68818743/0898d113-a743-4efd-b098-8e85f0feffd2)
I don't know if this is the correct trajectory. I download this dataset via `wget` and manually change the file name to `2D_CFD_Rand_M0.1_Eta0.1_Zeta0.1_periodic_128_Train.hdf5`. Some trajectory is 'normal' like: 
![屏幕截图 2024-04-25 190710](https://github.com/pdebench/PDEBench/assets/68818743/f122ef05-76c6-49d1-99c5-9bf7e4a4fc54)
I don't know if using `wget` is the reason that causing this. 
What's more, I try to check the continuity equation $\frac{\partial \rho}{\partial t} + \nabla(\rho \cdot \textbf{v}) = 0$, but it always fails as the formula $\frac{\partial \rho}{\partial t} + \nabla(\rho \cdot \textbf{v})$ equal to a non-zero value approximately the same scale as $\rho$ or $\textbf{v}$. I calculate those derivatives by using central difference method in temporal domain and spectral method in spatial domain.  So I think maybe something wrong with this dataset I downloaded. 

I don't know if you got some ideas here. Looking forward to your reply!

**Comment by kmario23** [comment]
FYI, this has been addressed in discussion thread https://github.com/pdebench/PDEBench/discussions/20
