### ISSUE TITLE
path error while generating burgers dataset

### ISSUE THREAD

**Issue by lin01109** [pdebench/PDEBench#65]
Hi! Thanks for all your work!
When I run command `CUDA_VISIBLE_DEVICES='0, 2’ python3 burgers_multi_solution_Hydra.py +multi=1e-3.yam` from `pdebench/data_gen/data_gen_NLE/BurgersEq/run_trainset.sh`, I seem to run into an error saving the path when running the command. What could be the cause? How can I solve this problem?
Here is the error log:
![image](https://github.com/pdebench/PDEBench/assets/62826276/bbc7c0f8-7ecc-4032-a31d-ed0f2fff23ca)
Thanks for any reply!

**Comment by kmario23** [comment]
This script is run inside the `BurgersEq` directory. Therefore, outside this directory you have to create a folder called `save` and then a `burgers` folder inside the `save` directory. Thereafter the script will write the generated numpy files.

Also, note that if you want to later train a surrogate model that we provide you've to serialize the `.npy` files to `.hdf5` files using the [`Data_Merge.py`](https://github.com/pdebench/PDEBench/blob/main/pdebench/data_gen/data_gen_NLE/Data_Merge.py) script.
