### ISSUE TITLE
question about data generation

### ISSUE THREAD

**Issue by lin01109** [pdebench/PDEBench#67]
Hi, there! Thanks for your great work. Recently I'm using your code to generate dataset. But I noticed that the code of saving dataset involved truncation of the parameter string. It seems that the  first five digits of the string are kept and the rest discarded. I wonder why this is done, is it for precision? Because when I try to generate a dataset with parameter 0.00101, the dataset name is only retained to 0.001, does this mean that the rest is out of precision? I hope you can understand my question and appreciate any reply.

Here's a snippet of code I've taken, and you can see that the dataset is named using only the first five digits of the parameter string

```    
    jnp.save(cwd+cfg.multi.save+'1D_Advection_Sols_beta'+str(beta)[:5], uu)
    jnp.save(cwd + cfg.multi.save + '/x_coordinate', xc)
    jnp.save(cwd + cfg.multi.save + '/t_coordinate', tc)

```
    jnp.save(cwd + cfg.multi.save+'/2D_ReacDiff_Multi_beta'+str(beta)[:5]+'_key'+str(cfg.multi.init_key), uu)
    jnp.save(cwd + cfg.multi.save+'/x_coordinate', xc)
    jnp.save(cwd + cfg.multi.save+'/y_coordinate', yc)
    jnp.save(cwd + cfg.multi.save+'/t_coordinate', tc)
    jnp.save(cwd + cfg.multi.save+'/nu_diff_coef_beta'+str(beta)[:5]+'_key'+str(cfg.multi.init_key), nu[:,2:-2,2:-2])
```
    jnp.save(cwd + cfg.multi.save+'/ReacDiff_Nu'+str(nu)[:5]+'_Rho'+str(rho)[:5], uu)
    jnp.save(cwd + cfg.multi.save+'/x_coordinate', xc)
    jnp.save(cwd + cfg.multi.save+'/t_coordinate', tc)

**Comment by kmario23** [comment]
No, the total precision is retained for data generation. This is evident from the lines:

- [reaction_diffusion_multi_solution_Hydra](https://github.com/pdebench/PDEBench/blob/main/pdebench/data_gen/data_gen_NLE/ReactionDiffusionEq/reaction_diffusion_multi_solution_Hydra.py#L186-L192)
- [advection_multi_solution_Hydra](https://github.com/pdebench/PDEBench/blob/main/pdebench/data_gen/data_gen_NLE/AdvectionEq/advection_multi_solution_Hydra.py#L188-L193)
- [reaction_diffusion_2D_multi_solution_Hydra](https://github.com/pdebench/PDEBench/blob/main/pdebench/data_gen/data_gen_NLE/ReactionDiffusionEq/reaction_diffusion_2D_multi_solution_Hydra.py#L265-L266)

For the purposes of serialization, we restrict the parameter digits to only 5 characters.

Having that said, note, however, that JAX enforces single-precision by default even if the data generation is done on the host with support for 64-bit. Moreover, for ML applications, it is generally not essential to have data with double precision.
